import { useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { Briefcase, Clock, DollarSign, TrendingUp } from 'lucide-react';

export default function ROIDashboard() {
  const data = [
    { name: 'TechCorp Analysis', hours: 45, value: 120000 },
    { name: 'HealthInc M&A', hours: 120, value: 450000 },
    { name: 'Retail Risk Audit', hours: 30, value: 50000 },
    { name: 'Energy Compliance', hours: 80, value: 210000 },
    { name: 'Finance LLC Fraud', hours: 60, value: 300000 },
  ];

  const totalHours = data.reduce((sum, item) => sum + item.hours, 0);
  const totalValue = data.reduce((sum, item) => sum + item.value, 0);
  const avgROI = totalValue / totalHours; // Value per hour

  return (
    <div className="space-y-6 animate-slide-up">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">Consulting ROI Dashboard</h1>
          <p className="text-gray-400">Track the value of insights generated vs time invested.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="glass-card p-6 border-t-4 border-t-blue-500">
          <div className="flex items-center gap-3 mb-2">
            <Clock className="text-blue-500" size={20} />
            <h3 className="text-gray-400 text-sm font-bold uppercase tracking-wider">Total Hours</h3>
          </div>
          <p className="text-3xl font-bold text-white">{totalHours} <span className="text-lg text-gray-500">hrs</span></p>
        </div>

        <div className="glass-card p-6 border-t-4 border-t-green-500">
          <div className="flex items-center gap-3 mb-2">
            <Briefcase className="text-green-500" size={20} />
            <h3 className="text-gray-400 text-sm font-bold uppercase tracking-wider">Value Uncovered</h3>
          </div>
          <p className="text-3xl font-bold text-white">${(totalValue / 1000).toFixed(0)}k</p>
        </div>

        <div className="glass-card p-6 border-t-4 border-t-gold col-span-2">
          <div className="flex items-center gap-3 mb-2">
            <TrendingUp className="text-gold" size={20} />
            <h3 className="text-gray-400 text-sm font-bold uppercase tracking-wider">Average ROI (Value per Hour)</h3>
          </div>
          <p className="text-3xl font-bold text-white">${avgROI.toFixed(0)} <span className="text-lg text-gray-500">/ hr</span></p>
          <p className="text-sm text-green-400 mt-2">+12% vs last quarter</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="glass-card p-6">
          <h3 className="text-xl font-bold mb-6">Value Generated by Engagement</h3>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={data} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" horizontal={false} />
                <XAxis type="number" stroke="#ffffff80" tickFormatter={v => `$${v/1000}k`} />
                <YAxis dataKey="name" type="category" stroke="#ffffff80" width={120} tick={{fontSize: 12}} />
                <Tooltip cursor={{fill: '#ffffff10'}} contentStyle={{ backgroundColor: '#0a1628', border: '1px solid #ffffff20' }} />
                <Bar dataKey="value" name="Value Uncovered ($)" radius={[0, 4, 4, 0]}>
                  {data.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.value > 200000 ? '#22c55e' : '#f0b429'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="glass-card p-6">
          <h3 className="text-xl font-bold mb-6">Most Valuable Analysis</h3>
          <div className="space-y-4">
            {data.sort((a,b) => b.value - a.value).map((item, idx) => (
              <div key={idx} className="flex justify-between items-center p-4 bg-white/5 rounded-lg border border-white/5 hover:border-white/20 transition-colors">
                <div>
                  <h4 className="font-bold text-white">{item.name}</h4>
                  <p className="text-xs text-gray-400 mt-1">{item.hours} hours invested</p>
                </div>
                <div className="text-right">
                  <div className="text-lg font-bold text-green-400">${(item.value / 1000).toFixed(0)}k</div>
                  <div className="text-xs text-gold font-bold">${(item.value / item.hours).toFixed(0)}/hr ROI</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
